# Generated by Django 3.0.2 on 2020-10-04 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_auto_20201003_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='tournament',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.Tournament'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
