# Generated by Django 3.0.2 on 2020-10-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_auto_20201004_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
